"""SQLite schema and access for the CARR dataset.

`data/carr.sqlite` is the scientific asset of this project: `problems`,
`configs` and `results` are free to rebuild, but every row in `generations`
cost real money. It is gitignored -- back it up separately.

Three properties this module exists to guarantee:

1. **Never pay twice.** `generations.request_hash` is UNIQUE over
   (model, effort, prompt, params). `insert_generation` checks it and returns
   None rather than raising, so a crashed run can be restarted and the
   already-bought rows cost $0 to skip.
2. **Mock rows can never be mistaken for real ones.** `generations.is_mock`
   is a real column, and every analysis query must filter on it. Without it a
   seeded row and a $0.0006 purchased row look identical.
3. **The grader's output shape is the results schema.** Columns mirror
   `carr.execute.verify.GradeResult` exactly, so there is no translation layer
   that could silently drop or rename a field.
"""

from __future__ import annotations

import hashlib
import json
import sqlite3
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_DB = ROOT / "data" / "carr.sqlite"

SCHEMA = """
-- One row per benchmark problem. Free to rebuild from evalplus.
CREATE TABLE IF NOT EXISTS problems (
    problem_id    TEXT PRIMARY KEY,      -- task_id, e.g. 'HumanEval/0'
    benchmark     TEXT NOT NULL,         -- humaneval_plus | mbpp_plus | livecodebench
    difficulty    TEXT,                  -- LCB provides this; HE+/MBPP+ are 'easy'
    prompt        TEXT NOT NULL,         -- sent to the model VERBATIM
    entry_point   TEXT NOT NULL,         -- function the tests call
    n_tests       INTEGER NOT NULL,      -- base + plus. A CARR router feature
    prompt_chars  INTEGER NOT NULL,      -- A CARR router feature
    n_base_tests  INTEGER NOT NULL,
    n_plus_tests  INTEGER NOT NULL,
    release_date  TEXT                   -- LCB only; contamination filtering
);

-- One row per (model x effort). Nine rows, from config/models.yaml.
CREATE TABLE IF NOT EXISTS configs (
    config_id        INTEGER PRIMARY KEY,
    model_slug       TEXT NOT NULL,
    family           TEXT NOT NULL,      -- within- vs cross-family routing analysis
    effort_label     TEXT NOT NULL,      -- off | high
    -- native_toggle and budget_forcing are NOT equivalent. Results must be
    -- splittable by mechanism or the effort axis is confounded.
    effort_mechanism TEXT NOT NULL,
    params_json      TEXT NOT NULL,      -- the exact `reasoning` block sent
    price_in_per_m   REAL NOT NULL,
    price_out_per_m  REAL NOT NULL,
    snapshot_date    TEXT NOT NULL,      -- prices move every 6-8 weeks
    held_out         INTEGER NOT NULL DEFAULT 0,
    subset_only      INTEGER NOT NULL DEFAULT 0,
    UNIQUE (model_slug, effort_label)
);

-- One row per API call. THE MONEY TABLE. Unrebuildable without paying again.
CREATE TABLE IF NOT EXISTS generations (
    gen_id             INTEGER PRIMARY KEY AUTOINCREMENT,
    problem_id         TEXT NOT NULL REFERENCES problems(problem_id),
    config_id          INTEGER NOT NULL REFERENCES configs(config_id),
    -- Checked BEFORE every call. This is what stops us buying a generation twice.
    request_hash       TEXT NOT NULL UNIQUE,
    openrouter_gen_id  TEXT,             -- for batched cost reconciliation
    raw_response       TEXT,             -- verbatim; enables free offline re-grading
    extracted_code     TEXT,             -- what actually gets executed
    prompt_tokens      INTEGER,
    completion_tokens  INTEGER,
    -- usage.completion_tokens_details.reasoning_tokens -- the field everyone
    -- misses. Day 1: 392 of 412 completion tokens were reasoning, invisible in
    -- the response text. Already INCLUDED in completion_tokens; never add twice.
    reasoning_tokens   INTEGER,
    cost_computed_usd  REAL,             -- tokens x the price table
    cost_actual_usd    REAL,             -- /generation total_cost -- ground truth
    finish_reason      TEXT,             -- stop | length. 'length' = hit max_tokens
    latency_ms         INTEGER,
    temperature_sent   REAL,             -- some endpoints override it silently
    error              TEXT,             -- NULL on success
    -- 1 = generated by carr/providers/echo.py, not bought. Every analysis query
    -- MUST filter is_mock = 0.
    is_mock            INTEGER NOT NULL DEFAULT 0,
    -- Echo provider only: which fixture shape produced this row (canonical,
    -- near_miss, ...). NULL for real generations. Lets us assert that every
    -- 'canonical' row graded PASS -- a mass-scale test_canonical_solutions_pass.
    mock_mode          TEXT,
    created_at         TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_gen_problem ON generations(problem_id);
CREATE INDEX IF NOT EXISTS idx_gen_config  ON generations(config_id);

-- One row per graded generation. Free to regenerate from raw_response.
-- Columns mirror carr.execute.verify.GradeResult exactly.
CREATE TABLE IF NOT EXISTS results (
    gen_id         INTEGER PRIMARY KEY REFERENCES generations(gen_id),
    passed         INTEGER NOT NULL,   -- survived BOTH base and plus tests
    base_passed    INTEGER NOT NULL,   -- original benchmark tests only
    n_tests_passed INTEGER NOT NULL,   -- diagnostic; pass@1 is binary
    n_tests_total  INTEGER NOT NULL,
    -- Constrained to what grade() actually emits. The specs also listed
    -- 'syntax' and 'exception'; nothing produces those, so they are not allowed
    -- in until something does.
    error_type     TEXT CHECK (error_type IN ('assertion', 'timeout')),
    exec_ms        INTEGER
);
"""


def connect(path: Path | str | None = None) -> sqlite3.Connection:
    """Open (creating parent dirs) and return a Row-factory connection."""
    p = Path(path or DEFAULT_DB)
    p.parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(p)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA foreign_keys = ON")
    return conn


def init_schema(conn: sqlite3.Connection) -> None:
    conn.executescript(SCHEMA)
    conn.commit()


def request_hash(model_slug: str, effort_label: str, prompt: str,
                 params: dict[str, Any]) -> str:
    """Stable id for one purchasable request.

    Deliberately covers exactly the four things that change what we get back.
    `json.dumps(sort_keys=True)` so dict ordering cannot produce two hashes for
    the same request -- that would mean buying the same generation twice.
    """
    payload = "\x00".join([
        model_slug,
        effort_label,
        prompt,
        json.dumps(params, sort_keys=True, separators=(",", ":")),
    ])
    return hashlib.sha256(payload.encode()).hexdigest()


# ---------------------------------------------------------------- writes


def upsert_problem(conn: sqlite3.Connection, *, problem_id: str, benchmark: str,
                   prompt: str, entry_point: str, n_base_tests: int,
                   n_plus_tests: int, difficulty: str | None = None,
                   release_date: str | None = None) -> None:
    conn.execute(
        """INSERT INTO problems (problem_id, benchmark, difficulty, prompt,
                                 entry_point, n_tests, prompt_chars,
                                 n_base_tests, n_plus_tests, release_date)
           VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
           ON CONFLICT(problem_id) DO UPDATE SET
               benchmark=excluded.benchmark, difficulty=excluded.difficulty,
               prompt=excluded.prompt, entry_point=excluded.entry_point,
               n_tests=excluded.n_tests, prompt_chars=excluded.prompt_chars,
               n_base_tests=excluded.n_base_tests,
               n_plus_tests=excluded.n_plus_tests,
               release_date=excluded.release_date""",
        (problem_id, benchmark, difficulty, prompt, entry_point,
         n_base_tests + n_plus_tests, len(prompt), n_base_tests, n_plus_tests,
         release_date),
    )


def upsert_config(conn: sqlite3.Connection, config_id: int, cfg) -> int:
    """Write one `carr.effort.Config`. `config_id` is its position in the
    cheapest-first ordering, so ids are stable across runs."""
    conn.execute(
        """INSERT INTO configs (config_id, model_slug, family, effort_label,
                                effort_mechanism, params_json, price_in_per_m,
                                price_out_per_m, snapshot_date, held_out,
                                subset_only)
           VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
           ON CONFLICT(model_slug, effort_label) DO UPDATE SET
               family=excluded.family,
               effort_mechanism=excluded.effort_mechanism,
               params_json=excluded.params_json,
               price_in_per_m=excluded.price_in_per_m,
               price_out_per_m=excluded.price_out_per_m,
               snapshot_date=excluded.snapshot_date,
               held_out=excluded.held_out,
               subset_only=excluded.subset_only""",
        (config_id, cfg.model_slug, cfg.family, cfg.effort_label,
         cfg.effort_mechanism, json.dumps(cfg.params, sort_keys=True),
         cfg.price_in_per_m, cfg.price_out_per_m, cfg.snapshot_date,
         int(cfg.held_out), int(cfg.subset_only)),
    )
    row = conn.execute(
        "SELECT config_id FROM configs WHERE model_slug = ? AND effort_label = ?",
        (cfg.model_slug, cfg.effort_label),
    ).fetchone()
    return row["config_id"]


def insert_generation(conn: sqlite3.Connection, **fields: Any) -> int | None:
    """Insert one generation, or return None if `request_hash` already exists.

    Returning None instead of raising is the point: the caller's loop treats a
    duplicate as "already bought, skip" rather than as an error to abort on.
    """
    fields.setdefault("created_at", datetime.now(timezone.utc).isoformat())
    cols = ", ".join(fields)
    marks = ", ".join("?" * len(fields))
    try:
        cur = conn.execute(
            f"INSERT INTO generations ({cols}) VALUES ({marks})",
            tuple(fields.values()),
        )
    except sqlite3.IntegrityError as exc:
        if "request_hash" in str(exc):
            return None
        raise
    return cur.lastrowid


def upsert_result(conn: sqlite3.Connection, gen_id: int, grade,
                  exec_ms: int | None = None) -> None:
    """Write a `carr.execute.verify.GradeResult`. Re-grading overwrites."""
    conn.execute(
        """INSERT INTO results (gen_id, passed, base_passed, n_tests_passed,
                                n_tests_total, error_type, exec_ms)
           VALUES (?, ?, ?, ?, ?, ?, ?)
           ON CONFLICT(gen_id) DO UPDATE SET
               passed=excluded.passed, base_passed=excluded.base_passed,
               n_tests_passed=excluded.n_tests_passed,
               n_tests_total=excluded.n_tests_total,
               error_type=excluded.error_type, exec_ms=excluded.exec_ms""",
        (gen_id, int(grade.passed), int(grade.base_passed), grade.n_tests_passed,
         grade.n_tests_total, grade.error_type, exec_ms),
    )


def has_generation(conn: sqlite3.Connection, req_hash: str) -> bool:
    """Cheap pre-flight check, so we never even build a paid request twice."""
    return conn.execute(
        "SELECT 1 FROM generations WHERE request_hash = ?", (req_hash,)
    ).fetchone() is not None


# ---------------------------------------------------------------- reads
# Shared by scripts/view.py and scripts/make_viewer.py so the terminal and
# the HTML page can never disagree about what the data says.


def list_configs(conn: sqlite3.Connection) -> list[sqlite3.Row]:
    return conn.execute(
        "SELECT * FROM configs ORDER BY price_out_per_m, model_slug, effort_label"
    ).fetchall()


def list_problems(conn: sqlite3.Connection) -> list[sqlite3.Row]:
    """Every problem with how many configs solved it."""
    return conn.execute(
        """SELECT p.*,
                  COUNT(g.gen_id)                       AS n_gens,
                  COALESCE(SUM(r.passed), 0)            AS n_passed,
                  MIN(CASE WHEN r.passed = 1 THEN g.cost_computed_usd END)
                                                        AS cheapest_pass_usd
           FROM problems p
           LEFT JOIN generations g ON g.problem_id = p.problem_id
           LEFT JOIN results r     ON r.gen_id = g.gen_id
           GROUP BY p.problem_id
           ORDER BY p.problem_id"""
    ).fetchall()


def get_problem(conn: sqlite3.Connection, problem_id: str) -> sqlite3.Row | None:
    return conn.execute(
        "SELECT * FROM problems WHERE problem_id = ?", (problem_id,)
    ).fetchone()


def rows_for_problem(conn: sqlite3.Connection, problem_id: str) -> list[sqlite3.Row]:
    """One row per config for this problem: the generation, its grade, its price."""
    return conn.execute(
        """SELECT g.*, c.model_slug, c.family, c.effort_label, c.effort_mechanism,
                  c.price_in_per_m, c.price_out_per_m, c.held_out,
                  r.passed, r.base_passed, r.n_tests_passed, r.n_tests_total,
                  r.error_type, r.exec_ms
           FROM generations g
           JOIN configs c ON c.config_id = g.config_id
           LEFT JOIN results r ON r.gen_id = g.gen_id
           WHERE g.problem_id = ?
           ORDER BY c.price_out_per_m, c.model_slug, c.effort_label""",
        (problem_id,),
    ).fetchall()


def cheapest_passing(conn: sqlite3.Connection, problem_id: str,
                     include_mock: bool = True) -> sqlite3.Row | None:
    """CARR's routing label: the cheapest config that actually solved this.

    This one query is what the whole schema exists to serve, and it is only
    computable if every problem ran through every config -- which is why the
    budget is cut by dropping problems, never by skipping grid cells.
    """
    mock_filter = "" if include_mock else "AND g.is_mock = 0"
    return conn.execute(
        f"""SELECT c.model_slug, c.effort_label, g.cost_computed_usd, g.gen_id
            FROM generations g
            JOIN results r  ON r.gen_id = g.gen_id
            JOIN configs c  ON c.config_id = g.config_id
            WHERE g.problem_id = ? AND r.passed = 1 {mock_filter}
            ORDER BY g.cost_computed_usd
            LIMIT 1""",
        (problem_id,),
    ).fetchone()


def summary(conn: sqlite3.Connection) -> dict[str, Any]:
    def scalar(sql: str) -> Any:
        return conn.execute(sql).fetchone()[0]

    return {
        "problems": scalar("SELECT COUNT(*) FROM problems"),
        "configs": scalar("SELECT COUNT(*) FROM configs"),
        "generations": scalar("SELECT COUNT(*) FROM generations"),
        "mock_generations": scalar("SELECT COUNT(*) FROM generations WHERE is_mock = 1"),
        "results": scalar("SELECT COUNT(*) FROM results"),
        "passed": scalar("SELECT COALESCE(SUM(passed), 0) FROM results"),
        "real_spend_usd": scalar(
            "SELECT COALESCE(SUM(COALESCE(cost_actual_usd, cost_computed_usd)), 0)"
            " FROM generations WHERE is_mock = 0"
        ),
    }
